# Site settings
title: "Emmanouela Vagianou Resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Emmanouela Vagianou"
resume_title:                   "Software Developer | HCI Master Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "emmavgn.0@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "6986104230"
resume_contact_address:         "Patras, Greece"

resume_header_contact_info:     "Patras, Greece • 6986104230 • emmavgn.0@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Motivated Software Engineer with a strong academic background in Computer Engineering and hands-on experience in full-stack web development, data integration, and consulting.  Academic interests focus on 
Web Development and Human-Computer Interaction, with emphasis on intuitive interface design, interactive web systems, and usability. Adaptable, team-oriented, and eager to contribute to innovative projects while advancing academic understanding through graduate study in HCI.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
#resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/kayieni"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/emmanouelavagianou"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
